<?php
/**
 * AgentUpdatePayloadTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Agent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace GeminiCommerce\Agent\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AgentUpdatePayloadTest Class Doc Comment
 *
 * @category    Class
 * @description AgentUpdatePayload
 * @package     GeminiCommerce\Agent
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AgentUpdatePayloadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AgentUpdatePayload"
     */
    public function testAgentUpdatePayload()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
