<?php
/**
 * AgentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  GeminiCommerce\Agent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * agent/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace GeminiCommerce\Agent\Test\Api;

use \GeminiCommerce\Agent\Configuration;
use \GeminiCommerce\Agent\ApiException;
use \GeminiCommerce\Agent\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AgentApiTest Class Doc Comment
 *
 * @category Class
 * @package  GeminiCommerce\Agent
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AgentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for agentCreateAgent
     *
     * .
     *
     */
    public function testAgentCreateAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for agentGetAgent
     *
     * .
     *
     */
    public function testAgentGetAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for agentListAgents
     *
     * .
     *
     */
    public function testAgentListAgents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for agentUpdateAgent
     *
     * .
     *
     */
    public function testAgentUpdateAgent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
